### ISSUE TITLE
[BUG] unitySDK相关问题

### ISSUE THREAD

**Issue by fuleiGitHub** [openimsdk/open-im-sdk-unity#7]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

创建聊天图片消息时，传入的图片的绝对路径，返回的图片消息中会有相关的URL吗？服务器端会处理图片的保存和生成一个对应的URL吗？还是说要通过自己的服务器来生成一个URL，赋值给图片消息传到聊天服务器上

**Comment by skiffer-git** [comment]
Both are fine.
